### ISSUE TITLE
Level stays in a Zoom-Out state the entire race

### ISSUE THREAD

**Issue by gcamantea** [topfreegames/bike-race-issues#1]
When a match is found in Duel, the level appears in a zoomed-out state.

**Expected behavior**: the level should zoom-in spontaneously shortly after appearing
**Observed behavior**: it stays in a zoomed-out state until the end
**Game Version**: 7.0.1

**Evidence**:
![17887572_1675759579108505_181963906_o](https://cloud.githubusercontent.com/assets/1260242/25023729/61e5eb20-2071-11e7-9243-0132a1110ccf.png)

**Comment by vkdaros** [comment]
Can anybody confirm that the problem persists in 7.0.2 please?
If so, how frequent does it happen?
Have you noticed any particular condition that triggers that behavior?

**Comment by vkdaros** [comment]
We haven't had any evidence that the problem still happens after v7.0.2
