### ISSUE TITLE
Duels Time issue

### ISSUE THREAD

**Issue by GodOfBikeRace** [topfreegames/bike-race-issues#14]
I don't know if you noticed that a lot of players are taking joke of their opponents, playing the level for over 70 seconds. I suggest you to set every level time again: you could take the 2 stars Single Player times.

**Comment by bruno1308** [comment]
As I believe this is happening with a minor set of levels, could you please tell us the levels that have this problem right now? (world-level)

**Comment by GodOfBikeRace** [comment]
I can't say precisely. I will try to test it with another player.

**Comment by bruno1308** [comment]
Closing the issue as the information needed wasn't provided. When you get the information needed, I can reopen the issue.
