### ISSUE TITLE
gas/brake stuck ON

### ISSUE THREAD

**Issue by mellasmonforte** [topfreegames/bike-race-issues#17]
Samsung Galaxy S8+ problem
I've been playing with the new phone for several days and noticed both the gas and brakes get stuck pretty often. One or the other gets stuck ON once every 10 minutes or so. This almost never happened in my old phone (Samsung Note 4)

**Comment by vkdaros** [comment]
Have you found a pattern that triggers the bug?
For example: Only happens in SinglePlayer; Happens when back wheel hits the ground first; etc.

You have Android 7.0 right?

**Comment by mellasmonforte** [comment]
I changed to play the game in full screen mode and I think the problem disappeared.  I play the latest beta version.
