### ISSUE TITLE
Duel Crash issue

### ISSUE THREAD

**Issue by GodOfBikeRace** [topfreegames/bike-race-issues#18]
It still happens, and people hate this.
.zip password: weloveguiga
[BUG OPPONENT.zip](https://github.com/topfreegames/bike-race-issues/files/967919/BUG.OPPONENT.zip)

**Comment by vkdaros** [comment]
With current information available to us right now we can't isolate the problem and take any action. We're improving our way to collect data and we'll attack the problem as soon as we identify the issue's root cause.
