### ISSUE TITLE
IOS Time Bug

### ISSUE THREAD

**Issue by Bawsified** [topfreegames/bike-race-issues#2]
Recently after deleting and reinstalling my times were reset
And now when I do complete a time it's only a matter of time till that time also resets 

**Version**: 7.3.5

**Comment by gcamantea** [comment]
By times you mean single player ranking times, right? Does that happen with times of all levels or just user created levels? Is your game connected to Facebook? If so, when you log in, do your times come back?

**Comment by Bawsified** [comment]
Yes single player times, there are some times on certain levels that saved, and I don't know about ucl's as I haven't ever kept track of that or noticed, and yes my game is connected to Facebook. When I log i really don't know, I have experienced times where the sp times are empty but only temporarily.

Also let me add the this note: I used to have an android tablet but I switched to iOS and when my times reset all my android times were put in place rather then my newer,  and better times I obtained on my iOS device 

1 more note: I'm not sure but when I play mp I think the time I get in a mp game (any mp game) overwrites my sp time on that level even if it's worse. (Not 100%)

**Comment by gcamantea** [comment]
Ok, thanks. Can you clarify which levels are saved and which are reset? Are times reset only on special tracks for example? What about Desert 1 levels? Are they reset too?

**Comment by Bawsified** [comment]
All des-1 levels are reset 
It's really tough to go through all levels and figure out if my times were saved or not 

Off the top of my head I remember none of the Easter level times saved, none of my dunes-1 times saved and there's plenty more. I don't remember the levels that did saved tho : /

**Comment by bruno1308** [comment]
7.4 should solve a lot of problems with account data saving/recovering
