### ISSUE TITLE
Duel Bike On Single Player

### ISSUE THREAD

**Issue by GodOfBikeRace** [topfreegames/bike-race-issues#20]
What about adding the Duel Bike on Single Player? In this way people could know which shortcuts are possible with one try. I'll upload two pics of my idea.
![before](https://cloud.githubusercontent.com/assets/27891393/26036541/d5ece880-38df-11e7-9d4c-a9cb8344f746.png)
![after](https://cloud.githubusercontent.com/assets/27891393/26036544/dc0b3032-38df-11e7-8091-a2ce138d1f24.png)

**Comment by guthyerrz** [comment]
We taught about this idea but it comes with certain problems. How do you combine this bike with Single Player Rankings and Multiplayer? We'd have to change a lot of existing features to show the current level of the opponent bike.
We might add this bike to SP but there is a big chance that it will always be on level 1.

**Comment by GodOfBikeRace** [comment]
What about adding it without counting its times in the ranking?
