### ISSUE TITLE
GodOfBikeRace² Duel Name

### ISSUE THREAD

**Issue by GodOfBikeRace** [topfreegames/bike-race-issues#21]
Guilherme told me to share this "issue". I can't change my name into GodOfBikeRace²
![18452491_10212882389037769_1201033660_o](https://cloud.githubusercontent.com/assets/27891393/26037651/ec720596-38f7-11e7-9179-fd5e7e26b584.png)
Cause it says that special characters are not allowed.
But I saw a player with that, how can I have it?
![18450018_10212882462799613_1731940278_n](https://cloud.githubusercontent.com/assets/27891393/26037663/30a9e2a6-38f8-11e7-9812-2344174c1642.png)
Can Guil or Guthyerzz change it in the database?

**Comment by guthyerrz** [comment]
We will review this restriction to see if there is any consequence to allow special characters. But since some people already have them it's possible we will remove this restriction.

**Comment by guthyerrz** [comment]
It'll be available on BikeRace in 7.6
