### ISSUE TITLE
mp stability

### ISSUE THREAD

**Issue by mellasmonforte** [topfreegames/bike-race-issues#22]
Long time issue (very long)
Well, I've been in China for 3 days now and it seems all my active mp races got stuck even though I now have wifi or 4g here. They were playing OK for a couple of days, but now they are stuck. Is there any way to make the mp system more robust? Doesn't TFG know if both mp players are waiting? VERY FRUSTRATING!!
Android (but I think all BR users experience this sometimes)

**Comment by vkdaros** [comment]
Hi Mellas
Please check v7.1.0 (beta). That version should unstuck your MP races.

**Comment by mellasmonforte** [comment]
I think the problem still exists.  I commented in the fb group a few days ago.  The races all appeared the day after I updated to the newest beta, but some were still stuck and now I think more have become stuck.

**Comment by vkdaros** [comment]
With the information we currently have, we can't identify your possibly stuck races. Could you send us your Facebook id and the id of some of your stuck opponents?

Please, notice that v7.0.4 is the last release. So it would be better if your list were made based on v7.1.0

**Comment by mellasmonforte** [comment]
my fb id is 100016617549250
some of my stuck races are with guest non-fb accounts.   2 guest account names would be: ->(Turbo)<-  AND Turbo
fb id's of stuck races (there are more if you need them)
759863137
100003719479733
100013540991021
100011008987573

**Comment by vkdaros** [comment]
We will investigate with that information.
Thank you very much!

**Comment by mellasmonforte** [comment]
Additional info:  as mentioned in the fb group, most of the stuck races will appear as normal bikes and waiting for me to return the race but they all disappear before I can race them.

**Comment by mellasmonforte** [comment]
additional info:
I was just chatting with a guy who in the past would load all his mp races, turn off data, play, turn on data.  No problem.  But over a year ago, something changed to where all his races would get stuck if he tried the same thing.

**Comment by vkdaros** [comment]
Version 7.1.0 has a fix to unstuck races.
