### ISSUE TITLE
time displays only 's'

### ISSUE THREAD

**Issue by mellasmonforte** [topfreegames/bike-race-issues#23]
Many times are showing up as 's'.  Before this best time, both our times only had 's'.  Using S8+ in 1480x720 mode. Also using game console to play this is FULL SCREEN MODE.

![screenshot_20170521-153054](https://cloud.githubusercontent.com/assets/27968520/26295519/3ca44164-3e98-11e7-9aec-a851c1187dc4.png)

**Comment by vkdaros** [comment]
Hi, Mellas
Have you tried to watch that replay or race against that ghost?
What I want to know is: Is that a problem in showing the time or doesn't the ghost have time?

**Comment by mellasmonforte** [comment]
you can watch the ghost. so I think it's just a time display problem

**Comment by vkdaros** [comment]
Update 7.2.0 fixes that.
