### ISSUE TITLE
Faster Animations Issue

### ISSUE THREAD

**Issue by GodOfBikeRace** [topfreegames/bike-race-issues#24]
My friend spotted faster animations in his Samsung A3, and I'm sure that other players are having the same problem - he has this bug since the first release of duels -.
I'll add a video in this thread, so you can check better.
[ANIMATIONS.zip](https://github.com/topfreegames/bike-race-issues/files/1039432/ANIMATIONS.zip)

**Comment by vkdaros** [comment]
It looks like your friend has changed Android animation speed scale in Developer Options. If he set that back to "1x" everything should work fine.
Please, check that with him.

![animation_speed](https://user-images.githubusercontent.com/211643/27077296-f37e19c2-5005-11e7-8f49-d8b4527bbb66.jpg)

**Comment by GodOfBikeRace** [comment]
You were right. It worked. Thanks for your help.
