### ISSUE TITLE
Restart a level takes some time

### ISSUE THREAD

**Issue by bruno1308** [topfreegames/bike-race-issues#25]
CJ Colson and Noah Borch reported a problem where pressing retry takes a while. It happens on every level

**Comment by NoahBorch** [comment]
Here is a video on the bug http://www.youtube.com/watch?v=3NVb7o2QQZs

**Comment by NoahBorch** [comment]
Also my iOS version is 10.2 and my device model is an IPhone 6

**Comment by bruno1308** [comment]
To be fixed on version 7.4.5

**Comment by bruno1308** [comment]
The restart time has improved, but it's still around 1 second, that is not acceptable

**Comment by bruno1308** [comment]
To be fixed on version 7.5.2, probably next week
