### ISSUE TITLE
Multiplayer and Tournaments Accounts Issue

### ISSUE THREAD

**Issue by GodOfBikeRace** [topfreegames/bike-race-issues#27]
An iOS player is complaining about the fact that he can't have two different Bike Race accounts linked with two different Facebook accounts. 
I'll explain. He uses FBaccount1 for Multiplayer and FBaccount2 for Tournaments. He logs into the FBaccount2 and he gets the Tournament account. When he logs into the FBaccount1 he gets his Multiplayer account but the game automatically update ALSO the Tournament account.

This is the main Tournament account, linked to FBaccount2:
![18870393_1852190421774096_1206516524_o](https://cloud.githubusercontent.com/assets/27891393/26764714/88486b52-496c-11e7-81e1-3895faf8f571.jpg)
This is the Tournament account that he gets once he logs into the FBaccount1:
![18927287_1852186451774493_601462194_o](https://cloud.githubusercontent.com/assets/27891393/26764726/d543f12e-496c-11e7-8687-b35e42ba1572.jpg)

**Comment by guthyerrz** [comment]
That's the intended behaviour. If he wants I can update his Tournaments account to use the facebook that he uses, so he can play Multiplayer and Tournaments using Facebook1. Ask him to talk to me on Facebook.
