### ISSUE TITLE
Time boost bug

### ISSUE THREAD

**Issue by MattiePvP** [topfreegames/bike-race-issues#29]
In all updates after 7.0, android has a slight start advantage seen in this video:
Active racing is on android version 7.0
Ghost time is on iOS 
https://www.facebook.com/matthijs.debruin.92/videos/1903164929967586/

**Comment by vkdaros** [comment]
This is a known bug and is present even in older versions (see video at [facebook](https://www.facebook.com/groups/1682240928731198/permalink/1883093771979245/?comment_id=1908977619390860&comment_tracking=%7B%22tn%22%3A%22R%22%7D)).
We will address this issue in the future.
