### ISSUE TITLE
Typo on 'Ninja Bike' description

### ISSUE THREAD

**Issue by Lawaleeth** [topfreegames/bike-race-issues#3]
Going to select the Ninja Bike, a spelling error is apparent in the description.

**Expected behavior:** Description reads "Ninja Bike"
**Observed behavior:** Description instead reads "Nija Bike" where "Nija" is not correctly spelled.
**Game version:** 7.3.6 (Bike Race Free)

**Evidence:** 
![image](https://cloud.githubusercontent.com/assets/17820926/25197343/6567680e-2509-11e7-8f03-3b5008fe7e22.png)

**Comment by bruno1308** [comment]
Will be fixed on 7.4
