### ISSUE TITLE
MATCHMAKING

### ISSUE THREAD

**Issue by Kunwar2005** [topfreegames/bike-race-issues#30]
I Dont have any major problem. But one thing for sure ;). The matchmaking now is so hard. And I would just leave a suggestion to bring back the old matchmaking. Its so hard to gain trophies at higher levels. No one even plays a match that high and even if someone does. You cant face them again. I kindly request the developers to bring back the old matchmaking. Thanks ;)

**Comment by MattiePvP** [comment]
This will not happen. The old match making brought up even more complaints, plus the new match making prevents self-boosting; a form of cheating.

**Comment by bruno1308** [comment]
Mattie explained well why it will not be done. Thanks for the suggestion anyway.
