### ISSUE TITLE
Time Bug/Early Start time

### ISSUE THREAD

**Issue by Yatasu** [topfreegames/bike-race-issues#32]
It is an occurrence that at the moment only android players are dealing with on the current update. It gives a slight advantage in the start like if the bike starts sooner than what it used to. so old WRs on very hard maps to beat like des 1-1 ghost acro hog normal etc are easily broken because of this bug. This bug is major because of the competitive mindset bike racers have with wanting to become the best racer around beating others WRs

**Comment by vkdaros** [comment]
We've run a sequence of test in a complete flat UCL (5fuv92), using last Android version, v6.9 and an iPhone. Finishing times were different in every trial and the greatest difference was 0.02s.
Please, provide more information showing evidences of the issue as well as how we could reproduce (bike type, level number, etc).

**Comment by vkdaros** [comment]
Closed due lack of information.
