### ISSUE TITLE
Connection Troubles in Duels

### ISSUE THREAD

**Issue by GodOfBikeRace** [topfreegames/bike-race-issues#37]
Compared with Bike Race Pro, in Bike Race Free I get a lot of connection troubles. 
I noticed that I ALWAYS get a connection problem in the first race, and the randomly in the next ones.

**Comment by vkdaros** [comment]
I'm assuming you're talking about Android. Is that right?
I've tried a bunch of different scenarios, such as:
* Start the app, go straight to Duel, and start a race;
* Start the app, race a single player match, got to Duel, and start a race;
* Start the app, race a multiplayer match, got to Duel, and start a race;
* Same as above, but with app coming from background;
I haven't had any connection problem.

Please, give us more detailed information about what is happening, your setup (device, Android version, type of connection, etc.), and the steps to reproduce the issue.

**Comment by vkdaros** [comment]
Not enough information.
