### ISSUE TITLE
Shop having to load every time it is opened.

### ISSUE THREAD

**Issue by MattiePvP** [topfreegames/bike-race-issues#4]
When opening the shop, it has to load all the bikes every time you open it. It does not save any data. 

(See: video I send in the group)

**Comment by gcamantea** [comment]
Could you share more nformation in here, like the video evidence, your device model and game version?

**Comment by MattiePvP** [comment]
I could not get the video off my phone, however I did send it in the messenger app. Pm me if you want to see it again. I have an Huawei P9 Lite, running on the latest version

**Comment by MattiePvP** [comment]
@gcamantea

**Comment by vkdaros** [comment]
We are working on a major performance improvement at shop. It will be released in next update.
