### ISSUE TITLE
Coins/Challenges/Level Up

### ISSUE THREAD

**Issue by GodOfBikeRace** [topfreegames/bike-race-issues#5]
I suggest you to reduce the number of coins:
-in the challenges;
-in the free chests;
-in the winning rewards.
Once a player reaches a level after 10, after a short time, he is obliged to wait till the next levelling up with the full storage of coins and the not-opened challenges prizes.

**Comment by gcamantea** [comment]
We are considering balance changes in the amount of gold and time for upgrades. Thanks for thr suggestion.
