### ISSUE TITLE
Level screenshot in Duel Mode

### ISSUE THREAD

**Issue by GodOfBikeRace** [topfreegames/bike-race-issues#6]
It happened that the game didn't show up the screenshot of the level, before starting the countdown. Sometimes it's hard to understand which level is it, without the screenshot.

**Comment by gcamantea** [comment]
Can you describe a way to make it happen? My test here worked as expected.

**Comment by GodOfBikeRace** [comment]
I'll try to record it so you can see that.
Anyways, after clicking on "play", it searches my opponent and then it doesn't show up the screenshot of the level, but it directly zooms in towards the bike, during the countdown. It can be confusing with some levels.

**Comment by guthyerrz** [comment]
Is it iOS or android?

**Comment by GodOfBikeRace** [comment]
Android @guthyerrz

**Comment by vkdaros** [comment]
Fixed in v7.2.0
